name: CD Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Release Workflow"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  deploy-application:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set up Docker Buildx
        id:   setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Fly.io Container Registry
        run: flyctl auth docker

      - name: Pull machine image
        run: docker pull ghcr.io/devolthq/devolt-validator:main

      - name: Tag validator image to Fly.io Container Registry
        run:  docker tag ghcr.io/devolthq/devolt-validator:main registry.fly.io/devolt:latest

      - name: Push validator image to Fly.io Container Registry
        run:  docker push registry.fly.io/devolt:latest

      - name: Deploy application
        run:  flyctl deploy -a devolt
