name: CI Workflow

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Go Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
          args: --timeout=5m

      - name: Run Go tests
        run: make test
